@host=http://localhost:5183

POST {{host}}/authentication/register
Content-Type: application/json

{
    "FirstName": "Apostolos",
    "LastName": "Grigoris",
    "Email": "gregapos@sampleMail.com",
    "Password": "S@mplePassword1"
}